"""empty message

Revision ID: 21f2e435aa3a
Revises: 3d7e34c6098a
Create Date: 2017-03-07 11:31:01.973000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f2e435aa3a'
down_revision = '3d7e34c6098a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'chartContainer_containerSize_id_fkey', 'chartContainer', type_='foreignkey')
    op.drop_constraint(u'chartContainer_chartType_id_fkey', 'chartContainer', type_='foreignkey')
    op.drop_column('chartContainer', 'containerSize_id')
    op.drop_column('chartContainer', 'chartType_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chartContainer', sa.Column('chartType_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chartContainer', sa.Column('containerSize_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'chartContainer_chartType_id_fkey', 'chartContainer', 'chartType', ['chartType_id'], ['id'])
    op.create_foreign_key(u'chartContainer_containerSize_id_fkey', 'chartContainer', 'containerSize', ['containerSize_id'], ['id'])
    # ### end Alembic commands ###
