"""empty message

Revision ID: 26365d5905f3
Revises: 5128f33f6556
Create Date: 2017-02-24 12:31:13.849000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26365d5905f3'
down_revision = '5128f33f6556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsibilityAssignment', sa.Column('reference_uuid', sa.String(), nullable=True))
    op.drop_constraint(u'responsibilityAssignment_responsibilityObject_id_reference__key', 'responsibilityAssignment', type_='unique')
    op.create_unique_constraint(None, 'responsibilityAssignment', ['responsibilityObject_id', 'reference_uuid', 'responsibilityType_id', 'user_uuid'])
    op.drop_column('responsibilityAssignment', 'reference_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsibilityAssignment', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'responsibilityAssignment', type_='unique')
    op.create_unique_constraint(u'responsibilityAssignment_responsibilityObject_id_reference__key', 'responsibilityAssignment', ['responsibilityObject_id', 'reference_id', 'responsibilityType_id', 'user_uuid'])
    op.drop_column('responsibilityAssignment', 'reference_uuid')
    # ### end Alembic commands ###
