"""empty message

Revision ID: 3d7e34c6098a
Revises: 6d76ba6bedea
Create Date: 2017-03-07 10:28:35.764000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7e34c6098a'
down_revision = '6d76ba6bedea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=True),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashContainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_uuid', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('chartContainer_id', sa.Integer(), nullable=True),
    sa.Column('dash_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chartContainer_id'], ['chartContainer.id'], ),
    sa.ForeignKeyConstraint(['dash_id'], ['dash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'chartContainer', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'chartContainer', sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('dashContainer')
    op.drop_table('dash')
    # ### end Alembic commands ###
