"""empty message

Revision ID: 402b35e40387
Revises: 751303139d51
Create Date: 2017-03-07 09:44:58.144000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402b35e40387'
down_revision = '751303139d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chartType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('chartContainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('startsize', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('chartType_id', sa.Integer(), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=True),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chartType_id'], ['chartType.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicatorChartType',
    sa.Column('chartType_id', sa.Integer(), nullable=True),
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chartType_id'], ['chartType.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicatorChartType')
    op.drop_table('chartContainer')
    op.drop_table('chartType')
    # ### end Alembic commands ###
