"""empty message

Revision ID: 52d0597ff2ec
Revises: 1eaffac078cf
Create Date: 2017-03-07 11:38:48.061000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d0597ff2ec'
down_revision = '1eaffac078cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_constraint(u'indicator_title_key', 'indicator', type_='unique')
#    op.drop_constraint(u'indicator_uuid_key', 'indicator', type_='unique')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'indicator_uuid_key', 'indicator', ['uuid'])
    op.create_unique_constraint(u'indicator_title_key', 'indicator', ['title'])
    # ### end Alembic commands ###
