"""empty message

Revision ID: 6c59f9c0acdb
Revises: 52d0597ff2ec
Create Date: 2017-03-07 11:43:28.584000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c59f9c0acdb'
down_revision = '52d0597ff2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_foreign_key(None, 'indicatorTarget', 'indicator', ['indicator_uuid'], ['uuid'])
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indicatorTarget', type_='foreignkey')
    # ### end Alembic commands ###
