"""empty message

Revision ID: 6e6f04e85671
Revises: 21f2e435aa3a
Create Date: 2017-03-07 11:34:24.377000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6f04e85671'
down_revision = '21f2e435aa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chartContainer', sa.Column('chartType_id', sa.Integer(), nullable=True))
    op.add_column('chartContainer', sa.Column('containerSize_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chartContainer', 'chartType', ['chartType_id'], ['id'])
    op.create_foreign_key(None, 'chartContainer', 'containerSize', ['containerSize_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chartContainer', type_='foreignkey')
    op.drop_constraint(None, 'chartContainer', type_='foreignkey')
    op.drop_column('chartContainer', 'containerSize_id')
    op.drop_column('chartContainer', 'chartType_id')
    # ### end Alembic commands ###
