"""empty message

Revision ID: 751303139d51
Revises: ce2cec01820c
Create Date: 2017-02-28 10:24:44.913313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '751303139d51'
down_revision = 'ce2cec01820c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicatorTarget', sa.Column('fromTarget', sa.Float(), nullable=True))
    op.add_column('indicatorTarget', sa.Column('toTarget', sa.Float(), nullable=True))
    op.drop_column('indicatorTarget', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicatorTarget', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('indicatorTarget', 'toTarget')
    op.drop_column('indicatorTarget', 'fromTarget')
    # ### end Alembic commands ###
