"""empty message

Revision ID: a323e1f9ad29
Revises: 6c59f9c0acdb
Create Date: 2017-03-07 11:44:54.158000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a323e1f9ad29'
down_revision = '6c59f9c0acdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'indicator', ['uuid'])
    op.create_foreign_key(None, 'indicatorTarget', 'indicator', ['indicator_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indicatorTarget', type_='foreignkey')
    op.drop_constraint(None, 'indicator', type_='unique')
    # ### end Alembic commands ###
