"""empty message

Revision ID: ce2cec01820c
Revises: 930a9dca5322
Create Date: 2017-02-27 12:12:05.215000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2cec01820c'
down_revision = '930a9dca5322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicatorTarget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('tenant_uuid', sa.String(), nullable=True),
    sa.Column('indicator_uuid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('validFrom', sa.Integer(), nullable=True),
    sa.Column('validTo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_uuid'], ['indicator.uuid'], ),
    sa.ForeignKeyConstraint(['validFrom'], ['calendar.id'], ),
    sa.ForeignKeyConstraint(['validTo'], ['calendar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicatorTarget')
    # ### end Alembic commands ###
